In [3]:
import pandas as pd
URL = 'https://companiesmarketcap.com/banks/largest-banks-by-market-cap/'
tables = pd.read_html(URL)
df = tables[0]
print(df)

    Unnamed: 0 Rank                                 Name Market Cap    Price  \
0          NaN    1                    JPMorgan ChaseJPM  $853.93 B  $310.55
1          NaN    2                  Bank of America BAC  $396.38 B   $53.52
2          NaN    3  Agricultural Bank of China601288.SS  $395.45 B    $1.13
3          NaN    4                          ICBC1398.HK  $370.63 B    $0.83
4          NaN    5     China Construction Bank601939.SS  $357.00 B    $1.36
..         ...  ...                                  ...        ...      ...
97         NaN   96                          M&T BankMTB   $29.83 B  $190.89
98         NaN   97                Fifth Third Bank FITB   $29.04 B   $43.94
99         NaN   98                Bank Hapoalim POLI.TA   $28.68 B   $21.80
100        NaN   99        National Bank of KuwaitNBK.KW   $28.50 B   $3,261
101        NaN  100       Svenska Handelsbanken SHB-A.ST   $28.06 B   $14.00

     Today Price (30 days)    Country
0    0.81%             NaN     🇺🇸 USA
1    0.25%             NaN     🇺🇸 USA
2    0.62%             NaN   🇨🇳 China
3    0.31%             NaN   🇨🇳 China
4    0.10%             NaN   🇨🇳 China
..     ...             ...        ...
97   1.15%             NaN     🇺🇸 USA
98   1.12%             NaN     🇺🇸 USA
99   0.00%             NaN  🇮🇱 Israel
100  0.30%             NaN  🇰🇼 Kuwait
101  0.65%             NaN  🇸🇪 Sweden

[102 rows x 8 columns]

In [4]:
df.head()

,Unnamed: 0,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,NaN,1,JPMorgan ChaseJPM,$853.93 B,$310.55,0.81%,NaN,🇺🇸 USA
1,NaN,2,Bank of America BAC,$396.38 B,$53.52,0.25%,NaN,🇺🇸 USA
2,NaN,3,Agricultural Bank of China601288.SS,$395.45 B,$1.13,0.62%,NaN,🇨🇳 China
3,NaN,4,ICBC1398.HK,$370.63 B,$0.83,0.31%,NaN,🇨🇳 China
4,NaN,5,China Construction Bank601939.SS,$357.00 B,$1.36,0.10%,NaN,🇨🇳 China

In [5]:
df.drop(columns=['Unnamed: 0'])

,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,1,JPMorgan ChaseJPM,$853.93 B,$310.55,0.81%,NaN,🇺🇸 USA
1,2,Bank of America BAC,$396.38 B,$53.52,0.25%,NaN,🇺🇸 USA
2,3,Agricultural Bank of China601288.SS,$395.45 B,$1.13,0.62%,NaN,🇨🇳 China
3,4,ICBC1398.HK,$370.63 B,$0.83,0.31%,NaN,🇨🇳 China
4,5,China Construction Bank601939.SS,$357.00 B,$1.36,0.10%,NaN,🇨🇳 China
...,...,...,...,...,...,...,...
97,96,M&T BankMTB,$29.83 B,$190.89,1.15%,NaN,🇺🇸 USA
98,97,Fifth Third Bank FITB,$29.04 B,$43.94,1.12%,NaN,🇺🇸 USA
99,98,Bank Hapoalim POLI.TA,$28.68 B,$21.80,0.00%,NaN,🇮🇱 Israel
100,99,National Bank of KuwaitNBK.KW,$28.50 B,"$3,261",0.30%,NaN,🇰🇼 Kuwait
101,100,Svenska Handelsbanken SHB-A.ST,$28.06 B,$14.00,0.65%,NaN,🇸🇪 Sweden

In [6]:
df.reset_index()

,index,Unnamed: 0,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,0,NaN,1,JPMorgan ChaseJPM,$853.93 B,$310.55,0.81%,NaN,🇺🇸 USA
1,1,NaN,2,Bank of America BAC,$396.38 B,$53.52,0.25%,NaN,🇺🇸 USA
2,2,NaN,3,Agricultural Bank of China601288.SS,$395.45 B,$1.13,0.62%,NaN,🇨🇳 China
3,3,NaN,4,ICBC1398.HK,$370.63 B,$0.83,0.31%,NaN,🇨🇳 China
4,4,NaN,5,China Construction Bank601939.SS,$357.00 B,$1.36,0.10%,NaN,🇨🇳 China
...,...,...,...,...,...,...,...,...,...
97,97,NaN,96,M&T BankMTB,$29.83 B,$190.89,1.15%,NaN,🇺🇸 USA
98,98,NaN,97,Fifth Third Bank FITB,$29.04 B,$43.94,1.12%,NaN,🇺🇸 USA
99,99,NaN,98,Bank Hapoalim POLI.TA,$28.68 B,$21.80,0.00%,NaN,🇮🇱 Israel
100,100,NaN,99,National Bank of KuwaitNBK.KW,$28.50 B,"$3,261",0.30%,NaN,🇰🇼 Kuwait
101,101,NaN,100,Svenska Handelsbanken SHB-A.ST,$28.06 B,$14.00,0.65%,NaN,🇸🇪 Sweden

In [12]:
df.columns

Index(['Unnamed: 0', 'Rank', 'Name', 'Market Cap', 'Price', 'Today',
       'Price (30 days)', 'Country'],
      dtype='object')

In [13]:
df.set_index('Rank')

,Unnamed: 0,Name,Market Cap,Price,Today,Price (30 days),Country
Rank,,,,,,,
1,NaN,JPMorgan ChaseJPM,$853.93 B,$310.55,0.81%,NaN,🇺🇸 USA
2,NaN,Bank of America BAC,$396.38 B,$53.52,0.25%,NaN,🇺🇸 USA
3,NaN,Agricultural Bank of China601288.SS,$395.45 B,$1.13,0.62%,NaN,🇨🇳 China
4,NaN,ICBC1398.HK,$370.63 B,$0.83,0.31%,NaN,🇨🇳 China
5,NaN,China Construction Bank601939.SS,$357.00 B,$1.36,0.10%,NaN,🇨🇳 China
...,...,...,...,...,...,...,...
96,NaN,M&T BankMTB,$29.83 B,$190.89,1.15%,NaN,🇺🇸 USA
97,NaN,Fifth Third Bank FITB,$29.04 B,$43.94,1.12%,NaN,🇺🇸 USA
98,NaN,Bank Hapoalim POLI.TA,$28.68 B,$21.80,0.00%,NaN,🇮🇱 Israel
99,NaN,National Bank of KuwaitNBK.KW,$28.50 B,"$3,261",0.30%,NaN,🇰🇼 Kuwait
100,NaN,Svenska Handelsbanken SHB-A.ST,$28.06 B,$14.00,0.65%,NaN,🇸🇪 Sweden

In [16]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [17]:
df.head()

,Rank,Name,Market Cap,Price,Today,Price (30 days),Country
0,1,JPMorgan ChaseJPM,$853.93 B,$310.55,0.81%,NaN,🇺🇸 USA
1,2,Bank of America BAC,$396.38 B,$53.52,0.25%,NaN,🇺🇸 USA
2,3,Agricultural Bank of China601288.SS,$395.45 B,$1.13,0.62%,NaN,🇨🇳 China
3,4,ICBC1398.HK,$370.63 B,$0.83,0.31%,NaN,🇨🇳 China
4,5,China Construction Bank601939.SS,$357.00 B,$1.36,0.10%,NaN,🇨🇳 China

In [18]:
df.drop(columns=['Price'],inplace=True)

In [19]:
df.head()

,Rank,Name,Market Cap,Today,Price (30 days),Country
0,1,JPMorgan ChaseJPM,$853.93 B,0.81%,NaN,🇺🇸 USA
1,2,Bank of America BAC,$396.38 B,0.25%,NaN,🇺🇸 USA
2,3,Agricultural Bank of China601288.SS,$395.45 B,0.62%,NaN,🇨🇳 China
3,4,ICBC1398.HK,$370.63 B,0.31%,NaN,🇨🇳 China
4,5,China Construction Bank601939.SS,$357.00 B,0.10%,NaN,🇨🇳 China

In [20]:
df['Country'].value_counts()

Country
🇺🇸 USA            16
🇨🇳 China          14
🇨🇦 Canada          6
🇬🇧 UK              5
🇯🇵 Japan           5
🇮🇳 India           5
🇦🇺 Australia       5
🇧🇷 Brazil          4
🇸🇬 Singapore       3
🇫🇷 France          3
🇸🇪 Sweden          3
🇪🇸 Spain           3
🇮🇹 Italy           2
🇹🇼 Taiwan          2
🇮🇱 Israel          2
Close Ad X         2
🇩🇪 Germany         2
🇮🇩 Indonesia       2
🇦🇪 UAE             2
🇭🇰 Hong Kong       2
🇰🇼 Kuwait          2
🇸🇦 S. Arabia       2
🇰🇷 S. Korea        1
🇩🇰 Denmark         1
🇹🇷 Turkey          1
🇳🇱 Netherlands     1
🇦🇹 Austria         1
🇶🇦 Qatar           1
🇫🇮 Finland         1
🇷🇺 Russia          1
🇨🇭 Switzerland     1
🇲🇾 Malaysia        1
Name: count, dtype: int64

In [25]:
'1:2,3:4'.split(':')

['1', '2,3', '4']

In [26]:
for i in range(1,5):
    if i!=1:
        print(i)

2
3
4

In [30]:
a = [1,3,3,5,1,7,4]
a.sort()

a

[1, 1, 3, 3, 4, 5, 7]

In [32]:
import numpy as np

a = np.array([1,1,1,1])

a+1

array([2, 2, 2, 2])