In [1]:
import pandas as pd

In [3]:
weather_data = pd.read_csv('/Users/michalbando/Downloads/Różne/IT/Practima.io - Kurs DA/drive-download-20250827T154251Z-1-001/Moduł 3 - Python/Weather_Data.csv')

In [4]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          100 non-null    object
 1   Temperature  100 non-null    float64
 2   Humidity     100 non-null    float64
 3   Wind_Speed   100 non-null    float64
dtypes: float64(3), object(1)
memory usage: 3.3+ KB

In [5]:
weather_data

           Day  Temperature  Humidity  Wind_Speed
0   2023-01-01         28.8      55.4         8.7
1   2023-01-02         22.0      66.4        24.1
2   2023-01-03         24.9      31.2        18.7
3   2023-01-04         31.2      48.1         9.3
4   2023-01-05         29.3      69.6        23.9
..         ...          ...       ...         ...
95  2023-04-06         23.5      79.9        19.5
96  2023-04-07         20.1      67.7        10.4
97  2023-04-08         28.9      82.4         7.6
98  2023-04-09         20.6      46.4         6.1
99  2023-04-10         22.0      77.9        11.0

[100 rows x 4 columns]

In [8]:
weather_data['Day'] = weather_data['Day'].sort_values(ascending=False)

In [14]:
weather_data.set_index('Day', inplace = True)

In [15]:
weather_data

            Temperature  Humidity  Wind_Speed
Day
2023-01-01         28.8      55.4         8.7
2023-01-02         22.0      66.4        24.1
2023-01-03         24.9      31.2        18.7
2023-01-04         31.2      48.1         9.3
2023-01-05         29.3      69.6        23.9
...                 ...       ...         ...
2023-04-06         23.5      79.9        19.5
2023-04-07         20.1      67.7        10.4
2023-04-08         28.9      82.4         7.6
2023-04-09         20.6      46.4         6.1
2023-04-10         22.0      77.9        11.0

[100 rows x 3 columns]

In [18]:
weather_data.tail()

            Temperature  Humidity  Wind_Speed
Day
2023-04-06         23.5      79.9        19.5
2023-04-07         20.1      67.7        10.4
2023-04-08         28.9      82.4         7.6
2023-04-09         20.6      46.4         6.1
2023-04-10         22.0      77.9        11.0

In [19]:
library_data = pd.read_csv('/Users/michalbando/Downloads/Różne/IT/Practima.io - Kurs DA/drive-download-20250827T154251Z-1-001/Moduł 3 - Python/Library_Data.csv')

In [20]:
library_data.head()

,Checkout ID,Book ID,Title,Author,Year of Publication,Genre,Page Count,Price,User ID,User Type,Late Return Fee,Renewals,Book Condition
0,1,39,Book 1,Author 9,2022,Fiction,205,29.31,44,Student,10,0,Worn
1,2,29,Book 2,Author 24,1990,History,257,43.95,45,Student,10,0,Damaged
2,3,15,Book 3,Author 1,2016,Science,246,13.51,32,Professional,0,1,New
3,4,43,Book 4,Author 12,2002,Science,244,65.64,45,Professional,0,2,Worn
4,5,8,Book 5,Author 8,1992,Biography,219,40.29,47,Retired,5,3,Worn

In [21]:
orders = pd.read_csv('/Users/michalbando/Downloads/Różne/IT/Practima.io - Kurs DA/drive-download-20250827T154251Z-1-001/Moduł 3 - Python/Orders.csv')

In [22]:
orders

,order_id,customer_id,order_date,product,quantity,price,discount_code,status,shipped_date
0,5001,101,2024-02-01,Python Course,1,199.0,WELCOME10,completed,2024-02-02
1,5002,102,2024-02-10,Tableau License,2,99.0,NaN,completed,2024-02-12
2,5003,103,2024-03-01,SQL Workshop,1,149.0,SPRING5,completed,2024-03-02
3,5004,104,2024-03-18,Pandas Ebook,3,29.0,NONE,completed,2024-03-19
4,5005,104,2024-03-25,Python Course,1,199.0,WELCOME10,refunded,2024-03-26
5,5006,105,2024-04-07,Data Viz Kit,5,39.0,NaN,completed,2024-04-10
6,5007,106,2024-04-20,Python Course,2,199.0,VIP15,completed,2024-04-22
7,5008,107,2024-05-01,SQL Workshop,1,149.0,NaN,cancelled,NaN
8,5009,108,2024-05-11,Pandas Ebook,2,29.0,NaN,completed,2024-05-12
9,5010,109,2024-06-01,Data Viz Kit,1,39.0,SPRING5,completed,2024-06-03

In [36]:
orders = orders.rename(columns={'customer_id': 'User ID'})

In [37]:
orders

,order_id,User ID,order_date,product,quantity,price,discount_code,status,shipped_date
0,5001,101,2024-02-01,Python Course,1,199.0,WELCOME10,completed,2024-02-02
1,5002,102,2024-02-10,Tableau License,2,99.0,NaN,completed,2024-02-12
2,5003,103,2024-03-01,SQL Workshop,1,149.0,SPRING5,completed,2024-03-02
3,5004,104,2024-03-18,Pandas Ebook,3,29.0,NONE,completed,2024-03-19
4,5005,104,2024-03-25,Python Course,1,199.0,WELCOME10,refunded,2024-03-26
5,5006,105,2024-04-07,Data Viz Kit,5,39.0,NaN,completed,2024-04-10
6,5007,106,2024-04-20,Python Course,2,199.0,VIP15,completed,2024-04-22
7,5008,107,2024-05-01,SQL Workshop,1,149.0,NaN,cancelled,NaN
8,5009,108,2024-05-11,Pandas Ebook,2,29.0,NaN,completed,2024-05-12
9,5010,109,2024-06-01,Data Viz Kit,1,39.0,SPRING5,completed,2024-06-03