<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [ ]:
!pip install pandas
!pip install matplotlib

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [32]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [33]:
print(df.info(verbose=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Data columns (total 114 columns):
 #    Column                          Dtype
---   ------                          -----
 0    ResponseId                      int64
 1    MainBranch                      object
 2    Age                             object
 3    Employment                      object
 4    RemoteWork                      object
 5    Check                           object
 6    CodingActivities                object
 7    EdLevel                         object
 8    LearnCode                       object
 9    LearnCodeOnline                 object
 10   TechDoc                         object
 11   YearsCode                       object
 12   YearsCodePro                    object
 13   DevType                         object
 14   OrgSize                         object
 15   PurchaseInfluence               object
 16   BuyNewTool                      object
 17   BuildvsBuy                      object
 18   TechEndorse                     object
 19   Country                         object
 20   Currency                        object
 21   CompTotal                       float64
 22   LanguageHaveWorkedWith          object
 23   LanguageWantToWorkWith          object
 24   LanguageAdmired                 object
 25   DatabaseHaveWorkedWith          object
 26   DatabaseWantToWorkWith          object
 27   DatabaseAdmired                 object
 28   PlatformHaveWorkedWith          object
 29   PlatformWantToWorkWith          object
 30   PlatformAdmired                 object
 31   WebframeHaveWorkedWith          object
 32   WebframeWantToWorkWith          object
 33   WebframeAdmired                 object
 34   EmbeddedHaveWorkedWith          object
 35   EmbeddedWantToWorkWith          object
 36   EmbeddedAdmired                 object
 37   MiscTechHaveWorkedWith          object
 38   MiscTechWantToWorkWith          object
 39   MiscTechAdmired                 object
 40   ToolsTechHaveWorkedWith         object
 41   ToolsTechWantToWorkWith         object
 42   ToolsTechAdmired                object
 43   NEWCollabToolsHaveWorkedWith    object
 44   NEWCollabToolsWantToWorkWith    object
 45   NEWCollabToolsAdmired           object
 46   OpSysPersonal use               object
 47   OpSysProfessional use           object
 48   OfficeStackAsyncHaveWorkedWith  object
 49   OfficeStackAsyncWantToWorkWith  object
 50   OfficeStackAsyncAdmired         object
 51   OfficeStackSyncHaveWorkedWith   object
 52   OfficeStackSyncWantToWorkWith   object
 53   OfficeStackSyncAdmired          object
 54   AISearchDevHaveWorkedWith       object
 55   AISearchDevWantToWorkWith       object
 56   AISearchDevAdmired              object
 57   NEWSOSites                      object
 58   SOVisitFreq                     object
 59   SOAccount                       object
 60   SOPartFreq                      object
 61   SOHow                           object
 62   SOComm                          object
 63   AISelect                        object
 64   AISent                          object
 65   AIBen                           object
 66   AIAcc                           object
 67   AIComplex                       object
 68   AIToolCurrently Using           object
 69   AIToolInterested in Using       object
 70   AIToolNot interested in Using   object
 71   AINextMuch more integrated      object
 72   AINextNo change                 object
 73   AINextMore integrated           object
 74   AINextLess integrated           object
 75   AINextMuch less integrated      object
 76   AIThreat                        object
 77   AIEthics                        object
 78   AIChallenges                    object
 79   TBranch                         object
 80   ICorPM                          object
 81   WorkExp                         float64
 82   Knowledge_1                     object
 83   Knowledge_2                     object
 84   Knowledge_3                     object
 85   Knowledge_4                     object
 86   Knowledge_5                     object
 87   Knowledge_6                     object
 88   Knowledge_7                     object
 89   Knowledge_8                     object
 90   Knowledge_9                     object
 91   Frequency_1                     object
 92   Frequency_2                     object
 93   Frequency_3                     object
 94   TimeSearching                   object
 95   TimeAnswering                   object
 96   Frustration                     object
 97   ProfessionalTech                object
 98   ProfessionalCloud               object
 99   ProfessionalQuestion            object
 100  Industry                        object
 101  JobSatPoints_1                  float64
 102  JobSatPoints_4                  float64
 103  JobSatPoints_5                  float64
 104  JobSatPoints_6                  float64
 105  JobSatPoints_7                  float64
 106  JobSatPoints_8                  float64
 107  JobSatPoints_9                  float64
 108  JobSatPoints_10                 float64
 109  JobSatPoints_11                 float64
 110  SurveyLength                    object
 111  SurveyEase                      object
 112  ConvertedCompYearly             float64
 113  JobSat                          float64
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB
None

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [34]:
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [35]:
df['Country'].unique()

array(['United States of America',
       'United Kingdom of Great Britain and Northern Ireland', 'Canada',
       'Norway', 'Uzbekistan', 'Serbia', 'Poland', 'Philippines',
       'Bulgaria', 'Switzerland', 'India', 'Germany', 'Ireland', 'Italy',
       'Ukraine', 'Australia', 'Brazil', 'Japan', 'Austria',
       'Iran, Islamic Republic of...', 'France', 'Saudi Arabia',
       'Romania', 'Turkey', 'Nepal', 'Algeria', 'Sweden', 'Netherlands',
       'Croatia', 'Pakistan', 'Czech Republic',
       'Republic of North Macedonia', 'Finland', 'Slovakia',
       'Russian Federation', 'Greece', 'Israel', 'Belgium', 'Mexico',
       'United Republic of Tanzania', 'Hungary', 'Argentina', 'Portugal',
       'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon', 'Spain',
       'South Africa', 'Lithuania', 'Viet Nam', 'Dominican Republic',
       'Indonesia', 'Kosovo', 'Morocco', 'Taiwan', 'Georgia',
       'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria', 'Liechtenstein',
       'Denmark', 'Ecuador', 'Malaysia', 'Albania', 'Azerbaijan', 'Chile',
       'Ghana', 'Peru', 'Bolivia', 'Egypt', 'Luxembourg', 'Montenegro',
       'Cyprus', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Jordan',
       'Venezuela, Bolivarian Republic of...', 'Costa Rica', 'Jamaica',
       'Thailand', 'Nicaragua', 'Myanmar', 'Republic of Korea', 'Rwanda',
       'Bosnia and Herzegovina', 'Benin', 'El Salvador', 'Zimbabwe',
       'Afghanistan', 'Estonia', 'Malta', 'Uruguay', 'Belarus',
       'Colombia', 'Republic of Moldova', 'Isle of Man', 'Nomadic',
       'New Zealand', 'Palestine', 'Armenia', 'United Arab Emirates',
       'Maldives', 'Ethiopia', 'Fiji', 'Guatemala', 'Uganda',
       'Turkmenistan', 'Mauritius', 'Kenya', 'Cuba', 'Gabon', 'Bahamas',
       'South Korea', 'Iceland', 'Honduras', 'Hong Kong (S.A.R.)',
       "Lao People's Democratic Republic", 'Mongolia', 'Cambodia',
       'Madagascar', 'Angola', 'Democratic Republic of the Congo',
       'Syrian Arab Republic', 'Iraq', 'Namibia', 'Senegal', 'Kyrgyzstan',
       'Zambia', 'Swaziland', "Côte d'Ivoire", 'Kuwait', 'Tajikistan',
       'Burundi', 'Trinidad and Tobago', 'Mauritania', 'Sierra Leone',
       'Panama', 'Somalia', 'North Korea', 'Dominica', 'Guyana', 'Togo',
       'Oman', 'Barbados', 'Andorra',
       "Democratic People's Republic of Korea", 'Qatar', 'Sudan',
       'Cameroon', 'Papua New Guinea', 'Bahrain', 'Yemen', 'Malawi',
       'Burkina Faso', 'Congo, Republic of the...', 'Botswana',
       'Guinea-Bissau', 'Mozambique', 'Central African Republic',
       'Equatorial Guinea', 'Suriname', 'Belize',
       'Libyan Arab Jamahiriya', 'Cape Verde', 'Brunei Darussalam',
       'Bhutan', 'Guinea', 'Niger', 'Antigua and Barbuda', 'Mali',
       'Samoa', 'Lesotho', 'Saint Kitts and Nevis', 'Monaco',
       'Micronesia, Federated States of...', 'Haiti', nan, 'Nauru',
       'Liberia', 'Chad', 'Djibouti', 'Solomon Islands'], dtype=object)

In [37]:
# unique_countries = df['Country'].unique()
# unique_countries.sort()
# # print(unique_countries

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [ ]:
## Write your code here

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [38]:
df = pd.get_dummies(df, columns=['Employment'])

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [39]:
df.isna().sum().sort_values(ascending=False)

AINextMuch less integrated                                                                                                                               64289
AINextLess integrated                                                                                                                                    63082
AINextNo change                                                                                                                                          52939
AINextMuch more integrated                                                                                                                               51999
EmbeddedAdmired                                                                                                                                          48704
                                                                                                                                                         ...
Employment_Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed                    0
Employment_Employed, full-time;Student, full-time;Not employed, but looking for work                                                                         0
Employment_Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired                            0
Employment_Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired        0
Employment_Student, part-time;Retired                                                                                                                        0
Length: 223, dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [40]:
median_comp = df['ConvertedCompYearly'].median()
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(median_comp)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [41]:
df['RemoteWork'] = df['RemoteWork'].value_counts().idxmax()

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [42]:
df['ConvertedCompYearly_MinMax'] = (df['ConvertedCompYearly'] - df['ConvertedCompYearly'].min()) / (df['ConvertedCompYearly'].max() - df['ConvertedCompYearly'].min())

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [43]:
import numpy as np
df['ConvertedCompYearly_Log'] = np.log1p(df['ConvertedCompYearly'])

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [44]:
df['YearsCodePro'].value_counts()

YearsCodePro
2                     4168
3                     4093
5                     3526
10                    3251
4                     3215
Less than 1 year      2856
6                     2843
1                     2639
8                     2549
7                     2517
12                    1777
15                    1635
20                    1549
9                     1493
11                    1312
13                    1127
14                    1082
25                     998
16                     946
18                     867
17                     814
30                     689
24                     632
19                     516
22                     492
23                     448
26                     426
21                     380
27                     380
28                     342
35                     285
29                     196
40                     194
32                     194
34                     169
38                     134
33                     132
36                     119
31                     106
37                     104
45                      56
42                      55
39                      54
41                      51
More than 50 years      50
44                      42
43                      37
46                      21
50                      14
48                      14
49                      11
47                      10
Name: count, dtype: int64

In [45]:
df['YearsCodePro'] = df['YearsCodePro'].replace({'Less than 1 year': 0, 'More than 50 years': 51})
df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'], errors='coerce')
# df['YearsCodePro'] = df['YearsCodePro'].fillna('Unknown')

In [46]:
df['YearsCodePro'].value_counts()

YearsCodePro
2.0     4168
3.0     4093
5.0     3526
10.0    3251
4.0     3215
0.0     2856
6.0     2843
1.0     2639
8.0     2549
7.0     2517
12.0    1777
15.0    1635
20.0    1549
9.0     1493
11.0    1312
13.0    1127
14.0    1082
25.0     998
16.0     946
18.0     867
17.0     814
30.0     689
24.0     632
19.0     516
22.0     492
23.0     448
26.0     426
21.0     380
27.0     380
28.0     342
35.0     285
29.0     196
40.0     194
32.0     194
34.0     169
38.0     134
33.0     132
36.0     119
31.0     106
37.0     104
45.0      56
42.0      55
39.0      54
41.0      51
51.0      50
44.0      42
43.0      37
46.0      21
50.0      14
48.0      14
49.0      11
47.0      10
Name: count, dtype: int64

In [47]:
# df['YearsCodePro'].astype('float64')

In [ ]:
def categorize_experience(years):
    # Najpierw sprawdzamy, czy w ogóle jest tam liczba
    if pd.isna(years):
        return 'Unknown'

    # Teraz bezpiecznie porównujemy liczby
    if years <= 2:
        return 'Junior'
    elif years <= 5:
        return 'Intermediate'
    elif years <= 10:
        return 'Senior'
    else:
        return 'Expert'

# Tworzymy nową kolumnę
df['ExperienceLevel'] = df['YearsCodePro'].apply(categorize_experience)

In [49]:
df[['ExperienceLevel','YearsCodePro']]

      ExperienceLevel  YearsCodePro
0             Unknown           NaN
1              Expert          17.0
2              Expert          27.0
3             Unknown           NaN
4             Unknown           NaN
...               ...           ...
65432    Intermediate           3.0
65433         Unknown           NaN
65434    Intermediate           5.0
65435          Junior           2.0
65436         Unknown           NaN

[65437 rows x 2 columns]

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.